apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'go-server'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        # 1. Debug: выводим исходный __address__
        - source_labels: [__address__]
          action: replace
          target_label: debug_original_address

        # 2. Debug: IP пода
        - source_labels: [__meta_kubernetes_pod_ip]
          action: replace
          target_label: debug_pod_ip

        # 3. Debug: аннотация port
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: debug_pod_port

        # 4. Debug: все три вместе (покажет, как выглядит склейка)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: debug_combined
          separator: ";"
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true

        # Формируем __address__ = POD_IP:ANNOTATION_PORT
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__

        # Путь к метрикам
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
          replacement: $1

        # Копируем лейблы
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name